Pink: mcimage.h File Reference
mcimage.h File Reference
Development
This file holds the basic image allocation functions.
Functions
struct xvimage * allocimage (char *name, index_t rs, index_t cs, index_t ds, int32_t t)
Allocates an image object with the given size and type.
void razimage (struct xvimage *f)
fills the image with zeros description Sets every pixel of the image to binary zero.
void freeimage (struct xvimage *image)
Frees an image object.
void writeimage (struct xvimage *image, char *filename)
Writes an image to disk.
struct xvimage * readimage (const char *filename)
Reads an image from a file.
Detailed Description
This file holds the basic image allocation functions.
Pink
Author
Michel Couprie, 2009
Function Documentation
allocimage()
struct xvimage * allocimage (char * name, index_t rs, index_t cs, index_t ds, int32_t t) extern
Allocates an image object with the given size and type.
Parameters
name Not used
rs x-size
cs y-size
ds z-size
t t-size
Returns
The pointer to the image.
freeimage()
void freeimage (struct xvimage * image) extern
Frees an image object.
Parameters
image The pointer to the image
Referenced by pink::ujoi< pixel_type_ >::ujoi().
razimage()
void razimage (struct xvimage * f) extern
fills the image with zeros description Sets every pixel of the image to binary zero.
Parameters
f the input image
Returns
no return value
readimage()
struct xvimage * readimage (const char * filename) extern
Reads an image from a file.
Parameters
filename The name of the image file.
Returns
A Pointer to a newly allocated image.
Referenced by pink::ujoi< pixel_type_ >::ujoi().
writeimage()
void writeimage (struct xvimage * image, char * filename) extern
Writes an image to disk.
Parameters
image The pointer to the image
filename The file to write the image at.
Referenced by pink::ujoi< pixel_type_ >::ujoi().